### PR TITLE
Invalidate transaction when Execute Action throws an exception

### PR DESCRIPTION
**Pull request by ibarban**

### CODE REVIEW

**Comment by bantolov** [comment]
Please, expand the unit test to check that the full call stack is available in the exception (if possible). This will help to prevent that the future refactoring (from try-finally to try-catch) don't break this feature.

**Comment by ibarban** [comment]
Shouldn't be enough to check just the first line of the stack trace?
Currently in the test project the first line of the exception is
`at TestAction._Helper.InsertAndThrowException_Repository.<Execute>b__1(InsertAndThrowException parameters, DomRepository repository, IUserInfo userInfo) in c:\Users\ibarbancic\source\repos\Rhetos\Source\Rhetos\bin\Generated\ServerDom.Repositories.cs:line 4501`
so I should just check if the first line contains
`InsertAndThrowException_Repository.<Execute>b__`
and this shoould cover also the second line of the stack trace.
After that, if I try to go up in the stack trace I would depend on the implementation of the TestUtility.ShouldFail method.
Maybe there are some cases that I am missing.

**Comment by bantolov** [comment]
I agree. The first line should be enough.

**Comment by bantolov** [comment]
I agree. I thunk the first line should be enough.

**Pull request merged**
